title: Yeti Tools
description: De tools voor het bestuur
baseurl: "/docs"
permalink: pretty
search_enabled: true
lsi: false
safe: true
source: docs
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: just-the-docs/just-the-docs
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "default"
    values:
      layout: "docs"
  - scope:
      path: "assets/img"
    values:
      image: true
